export const lexicon = {
    "taste basics": [
        "sweet",
        "sour",
        "bitter",
        "salty",
    ],
    "fruity": [
        "fruity",
        "berry",
        "strawberry",
        "raspberry",
        "blueberry",
        "blackberry",
        "dried fruit",
        "raisin",
        "prune",
        "other fruit",
        "apple",
        "pear",
        "peach",
        "grape",
        "cherry",
        "pomegrante",
        "coconut",
        "pineapple",
        "citrus fruit",
        "lemon",
        "grapefruit",
        "orange",
        "lime"
    ],
    "sour/acid": [
        "sour",
        "sour aromatics",
        "acetic acid",
        "butyric acid",
        "isovaleric acid",
        "citric acid",
        "malic acid",
    ],
    "alcohol/fermented": [
        "alcohol",
        "whiskey",
        "winey",
        "fermented",
        "overripe/near fermented",
    ],
    "green/vegetative": [
        "olive oil",
        "raw",
        "under-ripe",
        "peapod",
        "green",
        "fresh",
        "dark green",
        "vegetative",
        "hay-like",
        "herb-like",
        "beany",
    ],
    "stale/papery": [
        "stale",
        "papery",
        "cardboard",
    ],
    "earthy": [
        "musty/earthy",
        "musty/dusty",
        "moldy/damp",
        "phenolic",
        "animalic",
        "meaty/brothy",
        "woody",
    ],
    "chemical": [
        "bitter",
        "salty",
        "medicinal",
        "rubber",
        "petroleum",
        "skunky",
    ],
    "roasted": [
        "tabacco",
        "pipe tobacco",
        "acrid",
        "ashy",
        "burnt",
        "smoky",
        "roasted",
        "brown, roast",
    ],
    "cereal": [
        "grain",
        "malt"
    ],
    "spices": [
        "pungent",
        "pepper",
        "anise",
        "nutmeg",
        "brown spice",
        "cinnamon",
        "clove",
    ],
    "nutty": [
        "nutty",
        "almond",
        "hazelnut",
        "peanuts"
    ],
    "cocoa": [
        "chocolate",
        "cocoa",
        "dark chocolate"
    ],
    "sweet": [
        "sweet",
        "molasses",
        "maple syrup",
        "brown sugar",
        "caramelized",
        "honey",
        "vanilla",
        "vanillin",
        "sweet aromatics",
        "overall sweet"
    ],
    "floral": [
        "floral",
        "rose",
        "jasmine",
        "chamomile",
        "black tea",
    ],
    "amplitude": [
        "overall impact",
        "blended",
        "longevity",
        "mody/fullness"
    ],
    "mouthfeel": [
        "mouth drying",
        "thickness",
        "metalic",
        "oily"
    ]
}
